# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cisco_ios_xr_ipv4_bgp_oper/bgp/instances/instance/instance_standby/attribute_filter_groups/attribute_filter_group/bgp_attrfilter_group_bag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cisco_ios_xr_ipv4_bgp_oper/bgp/instances/instance/instance_standby/attribute_filter_groups/attribute_filter_group/bgp_attrfilter_group_bag.proto',
  package='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group',
  syntax='proto3',
  serialized_pb=_b('\n\x90\x01\x63isco_ios_xr_ipv4_bgp_oper/bgp/instances/instance/instance_standby/attribute_filter_groups/attribute_filter_group/bgp_attrfilter_group_bag.proto\x12qcisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group\"J\n\x1d\x62gp_attrfilter_group_bag_KEYS\x12\x15\n\rinstance_name\x18\x01 \x01(\t\x12\x12\n\ngroup_name\x18\x02 \x01(\t\"\x9f\x02\n\x18\x62gp_attrfilter_group_bag\x12#\n\x1b\x61ttribute_filter_group_name\x18\x32 \x01(\t\x12\xb1\x01\n\x1b\x61ttribute_filter_entry_list\x18\x33 \x03(\x0b\x32\x8b\x01.cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_entry_bag\x12*\n\"attribute_filter_total_group_count\x18\x34 \x01(\r\"\xa1\x01\n\x18\x62gp_attrfilter_entry_bag\x12/\n\'attribute_filter_entry_requested_action\x18\x01 \x01(\t\x12*\n\"attribute_filter_entry_range_start\x18\x02 \x01(\r\x12(\n attribute_filter_entry_range_end\x18\x03 \x01(\rb\x06proto3')
)




_BGP_ATTRFILTER_GROUP_BAG_KEYS = _descriptor.Descriptor(
  name='bgp_attrfilter_group_bag_KEYS',
  full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_group_bag_KEYS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_name', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_group_bag_KEYS.instance_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='group_name', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_group_bag_KEYS.group_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=338,
)


_BGP_ATTRFILTER_GROUP_BAG = _descriptor.Descriptor(
  name='bgp_attrfilter_group_bag',
  full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_group_bag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attribute_filter_group_name', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_group_bag.attribute_filter_group_name', index=0,
      number=50, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute_filter_entry_list', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_group_bag.attribute_filter_entry_list', index=1,
      number=51, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute_filter_total_group_count', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_group_bag.attribute_filter_total_group_count', index=2,
      number=52, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=628,
)


_BGP_ATTRFILTER_ENTRY_BAG = _descriptor.Descriptor(
  name='bgp_attrfilter_entry_bag',
  full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_entry_bag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attribute_filter_entry_requested_action', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_entry_bag.attribute_filter_entry_requested_action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute_filter_entry_range_start', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_entry_bag.attribute_filter_entry_range_start', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute_filter_entry_range_end', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_entry_bag.attribute_filter_entry_range_end', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=631,
  serialized_end=792,
)

_BGP_ATTRFILTER_GROUP_BAG.fields_by_name['attribute_filter_entry_list'].message_type = _BGP_ATTRFILTER_ENTRY_BAG
DESCRIPTOR.message_types_by_name['bgp_attrfilter_group_bag_KEYS'] = _BGP_ATTRFILTER_GROUP_BAG_KEYS
DESCRIPTOR.message_types_by_name['bgp_attrfilter_group_bag'] = _BGP_ATTRFILTER_GROUP_BAG
DESCRIPTOR.message_types_by_name['bgp_attrfilter_entry_bag'] = _BGP_ATTRFILTER_ENTRY_BAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

bgp_attrfilter_group_bag_KEYS = _reflection.GeneratedProtocolMessageType('bgp_attrfilter_group_bag_KEYS', (_message.Message,), dict(
  DESCRIPTOR = _BGP_ATTRFILTER_GROUP_BAG_KEYS,
  __module__ = 'cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_group_bag_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_group_bag_KEYS)
  ))
_sym_db.RegisterMessage(bgp_attrfilter_group_bag_KEYS)

bgp_attrfilter_group_bag = _reflection.GeneratedProtocolMessageType('bgp_attrfilter_group_bag', (_message.Message,), dict(
  DESCRIPTOR = _BGP_ATTRFILTER_GROUP_BAG,
  __module__ = 'cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_group_bag_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_group_bag)
  ))
_sym_db.RegisterMessage(bgp_attrfilter_group_bag)

bgp_attrfilter_entry_bag = _reflection.GeneratedProtocolMessageType('bgp_attrfilter_entry_bag', (_message.Message,), dict(
  DESCRIPTOR = _BGP_ATTRFILTER_ENTRY_BAG,
  __module__ = 'cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_group_bag_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.attribute_filter_groups.attribute_filter_group.bgp_attrfilter_entry_bag)
  ))
_sym_db.RegisterMessage(bgp_attrfilter_entry_bag)


# @@protoc_insertion_point(module_scope)
