# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cisco_ios_xr_ipv4_ospf_oper/ospf/processes/process/default_vrf/route_information/summary_information/ospf_sh_route_summary.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cisco_ios_xr_ipv4_ospf_oper/ospf/processes/process/default_vrf/route_information/summary_information/ospf_sh_route_summary.proto',
  package='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information',
  syntax='proto3',
  serialized_pb=_b('\n\x80\x01\x63isco_ios_xr_ipv4_ospf_oper/ospf/processes/process/default_vrf/route_information/summary_information/ospf_sh_route_summary.proto\x12\x64\x63isco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information\"2\n\x1aospf_sh_route_summary_KEYS\x12\x14\n\x0cprocess_name\x18\x01 \x01(\t\"\xdf\x02\n\x15ospf_sh_route_summary\x12\x10\n\x08\x66\x61ilures\x18\x32 \x01(\r\x12\x88\x01\n\x0c\x66\x61ilure_time\x18\x33 \x01(\x0b\x32r.cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_time\x12\x17\n\x0f\x66\x61ilure_address\x18\x34 \x01(\t\x12\x8f\x01\n\x06\x63ommon\x18\x35 \x01(\x0b\x32\x7f.cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summ_common\"2\n\x0cospf_sh_time\x12\x0e\n\x06second\x18\x01 \x01(\r\x12\x12\n\nnanosecond\x18\x02 \x01(\r\"\xc2\x01\n\x19ospf_sh_route_summ_common\x12\x17\n\x0f\x65xternal_type1s\x18\x01 \x01(\r\x12\x17\n\x0f\x65xternal_type2s\x18\x02 \x01(\r\x12\x1c\n\x14\x65xternal_nssa_type1s\x18\x03 \x01(\r\x12\x1c\n\x14\x65xternal_nssa_type2s\x18\x04 \x01(\r\x12\x13\n\x0binter_areas\x18\x05 \x01(\r\x12\x13\n\x0bintra_areas\x18\x06 \x01(\r\x12\r\n\x05total\x18\x07 \x01(\rb\x06proto3')
)




_OSPF_SH_ROUTE_SUMMARY_KEYS = _descriptor.Descriptor(
  name='ospf_sh_route_summary_KEYS',
  full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary_KEYS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='process_name', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary_KEYS.process_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=285,
)


_OSPF_SH_ROUTE_SUMMARY = _descriptor.Descriptor(
  name='ospf_sh_route_summary',
  full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='failures', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary.failures', index=0,
      number=50, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failure_time', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary.failure_time', index=1,
      number=51, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failure_address', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary.failure_address', index=2,
      number=52, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='common', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary.common', index=3,
      number=53, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=639,
)


_OSPF_SH_TIME = _descriptor.Descriptor(
  name='ospf_sh_time',
  full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='second', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_time.second', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nanosecond', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_time.nanosecond', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=641,
  serialized_end=691,
)


_OSPF_SH_ROUTE_SUMM_COMMON = _descriptor.Descriptor(
  name='ospf_sh_route_summ_common',
  full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summ_common',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='external_type1s', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summ_common.external_type1s', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='external_type2s', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summ_common.external_type2s', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='external_nssa_type1s', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summ_common.external_nssa_type1s', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='external_nssa_type2s', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summ_common.external_nssa_type2s', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inter_areas', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summ_common.inter_areas', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intra_areas', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summ_common.intra_areas', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summ_common.total', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=694,
  serialized_end=888,
)

_OSPF_SH_ROUTE_SUMMARY.fields_by_name['failure_time'].message_type = _OSPF_SH_TIME
_OSPF_SH_ROUTE_SUMMARY.fields_by_name['common'].message_type = _OSPF_SH_ROUTE_SUMM_COMMON
DESCRIPTOR.message_types_by_name['ospf_sh_route_summary_KEYS'] = _OSPF_SH_ROUTE_SUMMARY_KEYS
DESCRIPTOR.message_types_by_name['ospf_sh_route_summary'] = _OSPF_SH_ROUTE_SUMMARY
DESCRIPTOR.message_types_by_name['ospf_sh_time'] = _OSPF_SH_TIME
DESCRIPTOR.message_types_by_name['ospf_sh_route_summ_common'] = _OSPF_SH_ROUTE_SUMM_COMMON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ospf_sh_route_summary_KEYS = _reflection.GeneratedProtocolMessageType('ospf_sh_route_summary_KEYS', (_message.Message,), dict(
  DESCRIPTOR = _OSPF_SH_ROUTE_SUMMARY_KEYS,
  __module__ = 'cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary_KEYS)
  ))
_sym_db.RegisterMessage(ospf_sh_route_summary_KEYS)

ospf_sh_route_summary = _reflection.GeneratedProtocolMessageType('ospf_sh_route_summary', (_message.Message,), dict(
  DESCRIPTOR = _OSPF_SH_ROUTE_SUMMARY,
  __module__ = 'cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary)
  ))
_sym_db.RegisterMessage(ospf_sh_route_summary)

ospf_sh_time = _reflection.GeneratedProtocolMessageType('ospf_sh_time', (_message.Message,), dict(
  DESCRIPTOR = _OSPF_SH_TIME,
  __module__ = 'cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_time)
  ))
_sym_db.RegisterMessage(ospf_sh_time)

ospf_sh_route_summ_common = _reflection.GeneratedProtocolMessageType('ospf_sh_route_summ_common', (_message.Message,), dict(
  DESCRIPTOR = _OSPF_SH_ROUTE_SUMM_COMMON,
  __module__ = 'cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summary_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.default_vrf.route_information.summary_information.ospf_sh_route_summ_common)
  ))
_sym_db.RegisterMessage(ospf_sh_route_summ_common)


# @@protoc_insertion_point(module_scope)
