# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cisco_ios_xr_ipv4_ospf_oper/ospf/processes/process/srms/policy/policy_ipv4/policy_ipv4_backup/policy_mi/srms_mi_t_b.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cisco_ios_xr_ipv4_ospf_oper/ospf/processes/process/srms/policy/policy_ipv4/policy_ipv4_backup/policy_mi/srms_mi_t_b.proto',
  package='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi',
  syntax='proto3',
  serialized_pb=_b('\nycisco_ios_xr_ipv4_ospf_oper/ospf/processes/process/srms/policy/policy_ipv4/policy_ipv4_backup/policy_mi/srms_mi_t_b.proto\x12gcisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi\"7\n\x10srms_mi_t_b_KEYS\x12\x14\n\x0cprocess_name\x18\x01 \x01(\t\x12\r\n\x05mi_id\x18\x02 \x01(\t\"\xaf\x02\n\x0bsrms_mi_t_b\x12\x0b\n\x03src\x18\x32 \x01(\t\x12\x0e\n\x06router\x18\x33 \x01(\t\x12\x0c\n\x04\x61rea\x18\x34 \x01(\t\x12{\n\x04\x61\x64\x64r\x18\x35 \x01(\x0b\x32m.cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.addr\x12\x0e\n\x06prefix\x18\x36 \x01(\r\x12\x11\n\tsid_start\x18\x37 \x01(\r\x12\x11\n\tsid_count\x18\x38 \x01(\r\x12\x13\n\x0blast_prefix\x18\x39 \x01(\t\x12\x16\n\x0elast_sid_index\x18: \x01(\r\x12\x15\n\rflag_attached\x18; \x01(\t\"\x1d\n\x0cin6_addr_t_b\x12\r\n\x05value\x18\x01 \x01(\t\"\xa6\x01\n\x04\x61\x64\x64r\x12\n\n\x02\x61\x66\x18\x01 \x01(\t\x12\x0c\n\x04ipv4\x18\x02 \x01(\t\x12\x83\x01\n\x04ipv6\x18\x03 \x01(\x0b\x32u.cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.in6_addr_t_bb\x06proto3')
)




_SRMS_MI_T_B_KEYS = _descriptor.Descriptor(
  name='srms_mi_t_b_KEYS',
  full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b_KEYS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='process_name', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b_KEYS.process_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mi_id', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b_KEYS.mi_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=285,
)


_SRMS_MI_T_B = _descriptor.Descriptor(
  name='srms_mi_t_b',
  full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b.src', index=0,
      number=50, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='router', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b.router', index=1,
      number=51, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b.area', index=2,
      number=52, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addr', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b.addr', index=3,
      number=53, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b.prefix', index=4,
      number=54, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sid_start', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b.sid_start', index=5,
      number=55, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sid_count', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b.sid_count', index=6,
      number=56, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_prefix', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b.last_prefix', index=7,
      number=57, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_sid_index', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b.last_sid_index', index=8,
      number=58, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flag_attached', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b.flag_attached', index=9,
      number=59, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=591,
)


_IN6_ADDR_T_B = _descriptor.Descriptor(
  name='in6_addr_t_b',
  full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.in6_addr_t_b',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.in6_addr_t_b.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=622,
)


_ADDR = _descriptor.Descriptor(
  name='addr',
  full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.addr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='af', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.addr.af', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ipv4', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.addr.ipv4', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ipv6', full_name='cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.addr.ipv6', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=625,
  serialized_end=791,
)

_SRMS_MI_T_B.fields_by_name['addr'].message_type = _ADDR
_ADDR.fields_by_name['ipv6'].message_type = _IN6_ADDR_T_B
DESCRIPTOR.message_types_by_name['srms_mi_t_b_KEYS'] = _SRMS_MI_T_B_KEYS
DESCRIPTOR.message_types_by_name['srms_mi_t_b'] = _SRMS_MI_T_B
DESCRIPTOR.message_types_by_name['in6_addr_t_b'] = _IN6_ADDR_T_B
DESCRIPTOR.message_types_by_name['addr'] = _ADDR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

srms_mi_t_b_KEYS = _reflection.GeneratedProtocolMessageType('srms_mi_t_b_KEYS', (_message.Message,), dict(
  DESCRIPTOR = _SRMS_MI_T_B_KEYS,
  __module__ = 'cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b_KEYS)
  ))
_sym_db.RegisterMessage(srms_mi_t_b_KEYS)

srms_mi_t_b = _reflection.GeneratedProtocolMessageType('srms_mi_t_b', (_message.Message,), dict(
  DESCRIPTOR = _SRMS_MI_T_B,
  __module__ = 'cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b)
  ))
_sym_db.RegisterMessage(srms_mi_t_b)

in6_addr_t_b = _reflection.GeneratedProtocolMessageType('in6_addr_t_b', (_message.Message,), dict(
  DESCRIPTOR = _IN6_ADDR_T_B,
  __module__ = 'cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.in6_addr_t_b)
  ))
_sym_db.RegisterMessage(in6_addr_t_b)

addr = _reflection.GeneratedProtocolMessageType('addr', (_message.Message,), dict(
  DESCRIPTOR = _ADDR,
  __module__ = 'cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.srms_mi_t_b_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.srms.policy.policy_ipv4.policy_ipv4_backup.policy_mi.addr)
  ))
_sym_db.RegisterMessage(addr)


# @@protoc_insertion_point(module_scope)
