# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cisco_ios_xr_ipv4_bgp_oper/bgp/instances/instance/instance_standby/vrfs/vrf/afs/af/advertised_path_counts/advertised_path_count/bgp_nbr_adv_cnt_bag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cisco_ios_xr_ipv4_bgp_oper/bgp/instances/instance/instance_standby/vrfs/vrf/afs/af/advertised_path_counts/advertised_path_count/bgp_nbr_adv_cnt_bag.proto',
  package='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count',
  syntax='proto3',
  serialized_pb=_b('\n\x99\x01\x63isco_ios_xr_ipv4_bgp_oper/bgp/instances/instance/instance_standby/vrfs/vrf/afs/af/advertised_path_counts/advertised_path_count/bgp_nbr_adv_cnt_bag.proto\x12\x7f\x63isco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count\"n\n\x18\x62gp_nbr_adv_cnt_bag_KEYS\x12\x15\n\rinstance_name\x18\x01 \x01(\t\x12\x10\n\x08vrf_name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x66_name\x18\x03 \x01(\t\x12\x18\n\x10neighbor_address\x18\x04 \x01(\t\"9\n\x13\x62gp_nbr_adv_cnt_bag\x12\"\n\x1amax_prefix_advertisedcount\x18\x32 \x01(\rb\x06proto3')
)




_BGP_NBR_ADV_CNT_BAG_KEYS = _descriptor.Descriptor(
  name='bgp_nbr_adv_cnt_bag_KEYS',
  full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count.bgp_nbr_adv_cnt_bag_KEYS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_name', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count.bgp_nbr_adv_cnt_bag_KEYS.instance_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vrf_name', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count.bgp_nbr_adv_cnt_bag_KEYS.vrf_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='af_name', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count.bgp_nbr_adv_cnt_bag_KEYS.af_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neighbor_address', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count.bgp_nbr_adv_cnt_bag_KEYS.neighbor_address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=397,
)


_BGP_NBR_ADV_CNT_BAG = _descriptor.Descriptor(
  name='bgp_nbr_adv_cnt_bag',
  full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count.bgp_nbr_adv_cnt_bag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_prefix_advertisedcount', full_name='cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count.bgp_nbr_adv_cnt_bag.max_prefix_advertisedcount', index=0,
      number=50, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=456,
)

DESCRIPTOR.message_types_by_name['bgp_nbr_adv_cnt_bag_KEYS'] = _BGP_NBR_ADV_CNT_BAG_KEYS
DESCRIPTOR.message_types_by_name['bgp_nbr_adv_cnt_bag'] = _BGP_NBR_ADV_CNT_BAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

bgp_nbr_adv_cnt_bag_KEYS = _reflection.GeneratedProtocolMessageType('bgp_nbr_adv_cnt_bag_KEYS', (_message.Message,), dict(
  DESCRIPTOR = _BGP_NBR_ADV_CNT_BAG_KEYS,
  __module__ = 'cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count.bgp_nbr_adv_cnt_bag_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count.bgp_nbr_adv_cnt_bag_KEYS)
  ))
_sym_db.RegisterMessage(bgp_nbr_adv_cnt_bag_KEYS)

bgp_nbr_adv_cnt_bag = _reflection.GeneratedProtocolMessageType('bgp_nbr_adv_cnt_bag', (_message.Message,), dict(
  DESCRIPTOR = _BGP_NBR_ADV_CNT_BAG,
  __module__ = 'cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count.bgp_nbr_adv_cnt_bag_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_ipv4_bgp_oper.bgp.instances.instance.instance_standby.vrfs.vrf.afs.af.advertised_path_counts.advertised_path_count.bgp_nbr_adv_cnt_bag)
  ))
_sym_db.RegisterMessage(bgp_nbr_adv_cnt_bag)


# @@protoc_insertion_point(module_scope)
