# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cisco_ios_xr_mpls_ldp_oper/mpls_ldp/global/standby/vrfs/vrf/neighbor_capabilities/neighbor_capability/ldp_nbr_cap_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cisco_ios_xr_mpls_ldp_oper/mpls_ldp/global/standby/vrfs/vrf/neighbor_capabilities/neighbor_capability/ldp_nbr_cap_info.proto',
  package='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability',
  syntax='proto3',
  serialized_pb=_b('\n|cisco_ios_xr_mpls_ldp_oper/mpls_ldp/global/standby/vrfs/vrf/neighbor_capabilities/neighbor_capability/ldp_nbr_cap_info.proto\x12\x65\x63isco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability\"Q\n\x15ldp_nbr_cap_info_KEYS\x12\x10\n\x08vrf_name\x18\x01 \x01(\t\x12\x0e\n\x06lsr_id\x18\x02 \x01(\t\x12\x16\n\x0elabel_space_id\x18\x03 \x01(\r\"\x9e\x02\n\x10ldp_nbr_cap_info\x12\x81\x01\n\x04sent\x18\x32 \x03(\x0b\x32s.cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_cap_desc\x12\x85\x01\n\x08received\x18\x33 \x03(\x0b\x32s.cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_cap_desc\"j\n\x0cldp_cap_desc\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1e\n\x16\x63\x61pability_data_length\x18\x03 \x01(\r\x12\x17\n\x0f\x63\x61pability_data\x18\x04 \x01(\tb\x06proto3')
)




_LDP_NBR_CAP_INFO_KEYS = _descriptor.Descriptor(
  name='ldp_nbr_cap_info_KEYS',
  full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_nbr_cap_info_KEYS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vrf_name', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_nbr_cap_info_KEYS.vrf_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lsr_id', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_nbr_cap_info_KEYS.lsr_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label_space_id', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_nbr_cap_info_KEYS.label_space_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=312,
)


_LDP_NBR_CAP_INFO = _descriptor.Descriptor(
  name='ldp_nbr_cap_info',
  full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_nbr_cap_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sent', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_nbr_cap_info.sent', index=0,
      number=50, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='received', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_nbr_cap_info.received', index=1,
      number=51, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=601,
)


_LDP_CAP_DESC = _descriptor.Descriptor(
  name='ldp_cap_desc',
  full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_cap_desc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_cap_desc.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_cap_desc.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='capability_data_length', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_cap_desc.capability_data_length', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='capability_data', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_cap_desc.capability_data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=603,
  serialized_end=709,
)

_LDP_NBR_CAP_INFO.fields_by_name['sent'].message_type = _LDP_CAP_DESC
_LDP_NBR_CAP_INFO.fields_by_name['received'].message_type = _LDP_CAP_DESC
DESCRIPTOR.message_types_by_name['ldp_nbr_cap_info_KEYS'] = _LDP_NBR_CAP_INFO_KEYS
DESCRIPTOR.message_types_by_name['ldp_nbr_cap_info'] = _LDP_NBR_CAP_INFO
DESCRIPTOR.message_types_by_name['ldp_cap_desc'] = _LDP_CAP_DESC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ldp_nbr_cap_info_KEYS = _reflection.GeneratedProtocolMessageType('ldp_nbr_cap_info_KEYS', (_message.Message,), dict(
  DESCRIPTOR = _LDP_NBR_CAP_INFO_KEYS,
  __module__ = 'cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_nbr_cap_info_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_nbr_cap_info_KEYS)
  ))
_sym_db.RegisterMessage(ldp_nbr_cap_info_KEYS)

ldp_nbr_cap_info = _reflection.GeneratedProtocolMessageType('ldp_nbr_cap_info', (_message.Message,), dict(
  DESCRIPTOR = _LDP_NBR_CAP_INFO,
  __module__ = 'cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_nbr_cap_info_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_nbr_cap_info)
  ))
_sym_db.RegisterMessage(ldp_nbr_cap_info)

ldp_cap_desc = _reflection.GeneratedProtocolMessageType('ldp_cap_desc', (_message.Message,), dict(
  DESCRIPTOR = _LDP_CAP_DESC,
  __module__ = 'cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_nbr_cap_info_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_capabilities.neighbor_capability.ldp_cap_desc)
  ))
_sym_db.RegisterMessage(ldp_cap_desc)


# @@protoc_insertion_point(module_scope)
