# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cisco_ios_xr_mpls_ldp_oper/mpls_ldp/global/active/vrfs/vrf/afs/af/interface_summary/ldp_intf_sum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cisco_ios_xr_mpls_ldp_oper/mpls_ldp/global/active/vrfs/vrf/afs/af/interface_summary/ldp_intf_sum.proto',
  package='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary',
  syntax='proto3',
  serialized_pb=_b('\nfcisco_ios_xr_mpls_ldp_oper/mpls_ldp/global/active/vrfs/vrf/afs/af/interface_summary/ldp_intf_sum.proto\x12Scisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary\"6\n\x11ldp_intf_sum_KEYS\x12\x10\n\x08vrf_name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x66_name\x18\x02 \x01(\t\"\xa9\x02\n\x0cldp_intf_sum\x12 \n\x18known_ip_interface_count\x18\x32 \x01(\r\x12&\n\x1eknown_ip_interface_ldp_enabled\x18\x33 \x01(\r\x12)\n!ldp_configured_attached_interface\x18\x34 \x01(\r\x12#\n\x1bldp_configured_te_interface\x18\x35 \x01(\r\x12\x1a\n\x12\x66orward_references\x18\x36 \x01(\r\x12\x1c\n\x14\x61uto_config_disabled\x18\x37 \x01(\r\x12\x13\n\x0b\x61uto_config\x18\x38 \x01(\r\x12\x30\n(auto_config_forward_reference_interfaces\x18\x39 \x01(\rb\x06proto3')
)




_LDP_INTF_SUM_KEYS = _descriptor.Descriptor(
  name='ldp_intf_sum_KEYS',
  full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum_KEYS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vrf_name', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum_KEYS.vrf_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='af_name', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum_KEYS.af_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=245,
)


_LDP_INTF_SUM = _descriptor.Descriptor(
  name='ldp_intf_sum',
  full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='known_ip_interface_count', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum.known_ip_interface_count', index=0,
      number=50, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='known_ip_interface_ldp_enabled', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum.known_ip_interface_ldp_enabled', index=1,
      number=51, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ldp_configured_attached_interface', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum.ldp_configured_attached_interface', index=2,
      number=52, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ldp_configured_te_interface', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum.ldp_configured_te_interface', index=3,
      number=53, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forward_references', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum.forward_references', index=4,
      number=54, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auto_config_disabled', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum.auto_config_disabled', index=5,
      number=55, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auto_config', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum.auto_config', index=6,
      number=56, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auto_config_forward_reference_interfaces', full_name='cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum.auto_config_forward_reference_interfaces', index=7,
      number=57, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=545,
)

DESCRIPTOR.message_types_by_name['ldp_intf_sum_KEYS'] = _LDP_INTF_SUM_KEYS
DESCRIPTOR.message_types_by_name['ldp_intf_sum'] = _LDP_INTF_SUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ldp_intf_sum_KEYS = _reflection.GeneratedProtocolMessageType('ldp_intf_sum_KEYS', (_message.Message,), dict(
  DESCRIPTOR = _LDP_INTF_SUM_KEYS,
  __module__ = 'cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum_KEYS)
  ))
_sym_db.RegisterMessage(ldp_intf_sum_KEYS)

ldp_intf_sum = _reflection.GeneratedProtocolMessageType('ldp_intf_sum', (_message.Message,), dict(
  DESCRIPTOR = _LDP_INTF_SUM,
  __module__ = 'cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum_pb2'
  # @@protoc_insertion_point(class_scope:cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.active.vrfs.vrf.afs.af.interface_summary.ldp_intf_sum)
  ))
_sym_db.RegisterMessage(ldp_intf_sum)


# @@protoc_insertion_point(module_scope)
